name = "immutable_lru"
version = "1.0.1"


description = "Immutable LRU cache"
licences = ["MIT"]
repository = { type = "github", user = "chrstntdd", repo = "immutable_lru" }
gleam = ">= 0.32.0"


[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
